### ISSUE TITLE
Is this code ready to be used?

### ISSUE THREAD

**Issue by aromanelli** [csm/java-enet#1]
Bugs keep even the simplest test case from running (NPE's, bad looping code w/counter, etc).

I'm just wondering if this code can be used, or is still (or was) being developed, and not ready for prime time?

Thanks.

**Comment by csm** [comment]
No, this was never finished. I just wrote a wrapper around the native library instead.

**Comment by aromanelli** [comment]
Thanks for the reply. Yep, noticed your other wrapper-based project too, trying to get it set up now.
